### ISSUE TITLE
Feedback on solved issues

### ISSUE THREAD

**Issue by remarcmij** [JawharBairakdar/HYF-2nd-Step#2]
Hi Mohamad, thanks for trying to clarify your homework, but I still have difficulty untangling your code to match them against the questions. The homework assignments allow us to check how well you understood the material we covered in class.  It becomes a bit difficult if we have to look in several places for the answer to a single question. For the new homework assignments, please try to give a single and complete answer for each question in the homework. Good luck!

**Comment by JawharBairakdar** [comment]
Thank you So much,
Yeah I'll try staying with the plane next times hopefully.
see You tomorrow:)
