### ISSUE TITLE
Feedback DOM manipulation homework

### ISSUE THREAD

**Issue by remarcmij** [JawharBairakdar/HYF-2nd-Step#3]
Hi Mohamad, here is my feedback on your DOM manipulation homework, in particular the Scopes.js file.

I have difficulty again matching your code against what was asked in the assigment.

For instance:

- Where is the array from step 1?
- Where is the object that matches the requirements from step 4: _"Each item (object) in this object should have the book ID you thought up in point 1 as a key, and it should have at least the following fields: title, language and author."_

You have defined a function called `s`. What does `s` mean? Is there a better name you could give it?

Your function `s` takes three parameters but you are calling it later without supplying it any parameters. So why would you define your function with those parameters if you are not using them?

You need read again about `for` loops because the `for` loop statement looks confused. I would expect something like this:

```js
for (let index = 0; index < allTogether.CONAN_IDs.length; index++) {
}
```

You are not using the variable `id` so you might as well remove it.

There is no need to do `textMode++` because you do not use this incremented value of `textMode`. Instead, a couple of lines further below you re-assign `textMode` to a completely new value.

Please look at a possible implementation of the homework that I adapted from Nagham's homework submission this week. Carefully study the code and compare it with was asked in the homework assignment. Feel free to ask questions on slack.  
  
https://github.com/remarcmij/class12-js/tree/master/week3/nagham-dom

**Comment by JawharBairakdar** [comment]
Hi Jim How are you,
Sorry for delaying the replay it just was a personal reason without do any thing for the last two days,
I promise you I'll make it more readable next time but it was a pseudo code if you notice witch time i posted my trello card.
For the First point They ask us the following:
> Open a new js file and start by declaring an array that contains 10 strings. These strings should be of book titles you have read (or made up) and be lowercase without spaces or special characters so that you can use these later as Id's. (Example: Harry Potter's - The Chamber of Secrets -> harry_potter_chamber_secrets).

So the main thing is about an (array) about a book i have read before or made I Just didn't think about books so i made an Array about episodes from Detective Conan series. I think it's okay if it's not i can modify it.

For The Second Point:
I have made an object that contain all the arrays inside it with this move I did contain all the Information for each book I Thought i completed it, But i didn't see the rest of the question Unfortunately Sorry for this point.

`s` Yes is not mean any thing and is not make any sense, Maybe sibling is better name 😃.
With giving my function `s` Three parameters i am just defining a variables I don't know if is't wrong 💔.

I noticed that now the `id` AND `textMode` are not usable in the for loop i don't know why i putted them there that time,
But the question _(Buy the way)_ is can i some day at some specific reason make a for loop like so?

`
for (let index = 0, index2 = 0; index < allTogether.CONAN_IDs.length; index++, index2++) {
}
`
I have checked Naghams Homework and we have talked about it at the school you can find the code i have made for the array of objects she Did in [file.js](https://github.com/JawharBairakdar/HYF-2nd-Step/blob/master/JsWeek3/file.js) I have a lot of comments sorry but keeping my fails for future knowing what i was:) .
I promise i will do't better next time I have left the language school being full time with HYF 💯.
