### ISSUE TITLE
Strings & Arrays Week 3

### ISSUE THREAD

**Issue by remarcmij** [JawharBairakdar/HYF-2nd-Step#4]
Hi Mohamad,

This piece of your homework works fine.

I was just wondering why you have put the arrays assignment part in an Immediately Invoked Function Expression (IIFE) and the rest not. I would expect either all of your code in the IIFE or no IIFE at all.

I also don't understand the purpose of the `theParticularBrand` argument of the fat arrow function. As it seems to  serve no purpose, you should leave it out so that you don't confuse people reading your code. (You might become confused yourself if you look back at your code in a year from now!)

**Comment by JawharBairakdar** [comment]
Hi Jim,
Yeah thank you.
The part under the IIFE section if we can call it like so is just making the Q.7 parts under it without any confusing for me or you as a person.
And `theParticularBranch` is just kind of title remembering me and you this is Q.7 parts I did commented 
`// Q.7 Followers` But in reason some body didn't looks to the comment he will notice that there.
In projects I'll never do that!.
